### ISSUE TITLE
Logs overwritten on server restart

### ISSUE THREAD

**Issue by oddoye-david** [mcollina/pino-elasticsearch#2]
Whenever i restart my server and pipe the logs into elasticsearch, all the old logs are overwritten. Is this normal? Same behavior with logging to a file. 

Great works as usual by the way.

**Comment by mcollina** [comment]
Thanks!

That is not the expected behavior, but I could not reproduce locally, the logs are persisted inside ElasticSearch. Can you please provide instructions on how to replicate?

Regarding the file case, you need to `node app.js >> file.log`, if you do `node app.js > file.log` the file will be overwritten at every restart.

**Comment by mcollina** [comment]
Closing for low activity. Feel free to reopen if this is still an issue for you.
